
services:

  postgres:
    container_name: postgres-junebank-v2
    image: postgres
    environment:
      POSTGRES_USER: muaz
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - database
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-junebank-v2
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - database
    restart: unless-stopped

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

#  redis:
#    container_name: redis_cache
#    image: redis:6.2-alpine
#    restart: always
#    ports:
#      - '6379:6379'
#    command: redis-application --save 20 1 --loglevel warning --requirepass password
#    volumes:
#      - redis:/data
#    environment:
#      REDIS_HOST: redis
#      REDIS_PORT: 6379
#      REDIS_PASSWORD: password
      


networks:
  database:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  kafka_data:
  zookeeper_data:
