version: '3.9'
services:
  mysql:
    image: mysql:8.0.31
    container_name: user-service-db
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: pass
        MYSQL_DATABASE: user
    volumes:
      - ./volumes/mysql:/var/lib/mysql